#read data.json and create male.json file and female.json file
import json
fp1=open("data.json",'r')
users=json.load(fp1)
print(type(users))
print(len(users))
male_users=list(filter(lambda user:user['gender']=='Male',users))
Female_users=list(filter(lambda user:user['gender']=='Female',users))
print(len(Female_users))
fp2=open("male.json",'w')
fp3=open("female.json",'w')
json.dump(male_users,fp2)
json.dump(Female_users,fp3)
fp1.close()
fp2.close()
fp3.close()